apiVersion: v1
kind: Service
metadata:
  name: sage-ui
  namespace: sage
spec:
  #type: NodePort #(ClusterIP  does not seem to work with ingress)
  ports:
  - port: 80
    protocol: TCP
    name: "http"
  selector:
    k8s-app: sage-ui

