apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sage-ui-db
  namespace: sage
spec:
  #storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
